### ISSUE TITLE
Error installing theme

### ISSUE THREAD

**Issue by joseterra** [orf/bare-hugo-theme#13]
What are the npm modules used and where should they be installed?

```
jose@pop-os:~/codes/projects/quickstart$ git submodule update --init --recursive
Submodule 'assets/css/bulma' (https://github.com/jgthms/bulma.git) registered for path 'themes/bare/assets/css/bulma'
Submodule 'assets/icons' (https://github.com/Templarian/MaterialDesign.git) registered for path 'themes/bare/assets/icons'
Cloning into '/home/jose/codes/projects/quickstart/themes/bare/assets/css/bulma'...
Cloning into '/home/jose/codes/projects/quickstart/themes/bare/assets/icons'...
Submodule path 'themes/bare/assets/css/bulma': checked out '11c44b09225b131378e9bae68d651b4948e3c598'
Submodule path 'themes/bare/assets/icons': checked out 'cc7073f19492004f4aee4d16c502f757bff15955'
jose@pop-os:~/codes/projects/quickstart$ hugo server
Building sites … ERROR 2019/10/16 12:50:51 Transformation failed: POSTCSS: failed to transform "css/site.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/
Total in 144 ms
Error: Error building site: logged 1 error(s)

```

```
jose@pop-os:~/codes/projects/quickstart$ npm install postcss-cli
npm WARN saveError ENOENT: no such file or directory, open '/home/jose/codes/projects/quickstart/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/jose/codes/projects/quickstart/package.json'
npm WARN quickstart No description
npm WARN quickstart No repository field.
npm WARN quickstart No README data
npm WARN quickstart No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ postcss-cli@6.1.3
added 253 packages from 190 contributors and audited 3244 packages in 11.403s
found 0 vulnerabilities



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.11.3 → 6.12.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.12.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯
``` 

```
jose@pop-os:~/codes/projects/quickstart$ hugo server
Building sites … Error: Loading PostCSS Plugin failed: Cannot find module '@fullhuman/postcss-purgecss'
Require stack:
- /home/jose/codes/projects/quickstart/noop.js

(@/home/jose/codes/projects/quickstart/themes/bare/postcss.config.js)
    at load (/home/jose/codes/projects/quickstart/node_modules/postcss-load-config/src/plugins.js:28:11)
    at /home/jose/codes/projects/quickstart/node_modules/postcss-load-config/src/plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (/home/jose/codes/projects/quickstart/node_modules/postcss-load-config/src/plugins.js:52:8)
    at processResult (/home/jose/codes/projects/quickstart/node_modules/postcss-load-config/src/index.js:33:14)
    at /home/jose/codes/projects/quickstart/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
ERROR 2019/10/16 12:51:31 Transformation failed: exit status 1
Total in 353 ms
Error: Error building site: logged 1 error(s)

```

**Comment by joseterra** [comment]
resolved problem, thank you
